# Generated by Django 3.2.16 on 2022-11-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0041_jobmodel_inner_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParetoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning shift', 'Morning shift'), ('Afternoon shift', 'Afternoon shift'), ('Night shift', 'Night shift')], default='Morning shift', max_length=32)),
                ('output', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tools.jobmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pareto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pareto_date', models.DateField()),
                ('shift', models.CharField(choices=[('Morning shift', 'Morning shift'), ('Afternoon shift', 'Afternoon shift'), ('Night shift', 'Night shift')], default='Morning shift', max_length=32)),
                ('completed', models.BooleanField(default=False)),
                ('jobs', models.ManyToManyField(to='gemba.ParetoDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
