# Generated by Django 3.2.16 on 2022-11-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paretodetail',
            name='date',
        ),
    ]
