# Generated by Django 3.2.16 on 2022-11-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0002_remove_paretodetail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paretodetail',
            name='shift',
        ),
    ]
