# Generated by Django 3.2.16 on 2022-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0004_auto_20221112_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Downtimes',
            },
        ),
        migrations.AlterModelOptions(
            name='pareto',
            options={'verbose_name': 'Pareto'},
        ),
        migrations.AlterModelOptions(
            name='paretodetail',
            options={'verbose_name': 'Pareto Details'},
        ),
    ]
