# Generated by Django 3.2.16 on 2022-11-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gemba', '0005_auto_20221112_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimemodel',
            options={'verbose_name': 'Downtime'},
        ),
        migrations.AlterModelOptions(
            name='paretodetail',
            options={'verbose_name': 'Pareto Detail'},
        ),
        migrations.CreateModel(
            name='DowntimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime', to='gemba.downtimemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Downtime Detail',
            },
        ),
    ]
