# Generated by Django 3.2.16 on 2022-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0006_auto_20221113_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='downtimes',
            field=models.ManyToManyField(to='gemba.DowntimeDetail'),
        ),
    ]
