# Generated by Django 3.2.16 on 2022-11-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0007_pareto_downtimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtimedetail',
            old_name='code',
            new_name='downtime',
        ),
    ]
