# Generated by Django 3.2.16 on 2022-11-13 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gemba', '0008_rename_code_downtimedetail_downtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Scrap reason',
            },
        ),
        migrations.CreateModel(
            name='ScrapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='gemba.downtimemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrap detail',
            },
        ),
        migrations.AddField(
            model_name='pareto',
            name='scrap',
            field=models.ManyToManyField(to='gemba.ScrapDetail'),
        ),
    ]
