# Generated by Django 3.2.16 on 2022-11-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0041_jobmodel_inner_size'),
        ('gemba', '0009_auto_20221113_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdetail',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs3', to='tools.jobmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapdetail',
            name='scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='gemba.scrapmodel'),
        ),
    ]
