# Generated by Django 3.2.16 on 2022-11-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0041_jobmodel_inner_size'),
        ('gemba', '0010_auto_20221113_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimedetail',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs5', to='tools.jobmodel'),
            preserve_default=False,
        ),
    ]
