# Generated by Django 3.2.16 on 2022-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0011_downtimedetail_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodetail',
            name='good',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
