# Generated by Django 3.2.16 on 2022-11-20 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0012_paretodetail_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pareto',
            name='shift',
        ),
        migrations.AddField(
            model_name='pareto',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
