# Generated by Django 3.2.16 on 2022-11-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0014_auto_20221125_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmodel',
            name='start',
            field=models.TimeField(),
        ),
    ]
