# Generated by Django 3.2.16 on 2022-11-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0015_alter_hourmodel_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pareto',
            name='time_stamp',
        ),
    ]
