# Generated by Django 3.2.16 on 2022-11-25 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0016_remove_pareto_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='time_stamp',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
