# Generated by Django 3.2.16 on 2022-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0017_pareto_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareto',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
