# Generated by Django 3.2.16 on 2022-12-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0020_jobuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimedetail',
            name='pareto_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='pareto_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='pareto_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='JobUser',
        ),
    ]
