# Generated by Django 3.2.16 on 2022-12-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0022_auto_20221207_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='ops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
