# Generated by Django 3.2.16 on 2022-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0023_pareto_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('target', models.IntegerField(default=1615)),
                ('inner_size', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Job',
            },
        ),
    ]
