# Generated by Django 3.2.16 on 2022-12-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0024_jobmodel2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimedetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs5', to='gemba.jobmodel2'),
        ),
        migrations.AlterField(
            model_name='paretodetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='gemba.jobmodel2'),
        ),
        migrations.AlterField(
            model_name='scrapdetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs3', to='gemba.jobmodel2'),
        ),
    ]
