# Generated by Django 3.2.16 on 2022-12-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0025_auto_20221211_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel2',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_group', to='gemba.downtimegroup'),
            preserve_default=False,
        ),
    ]
