# Generated by Django 3.2.16 on 2022-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0028_segment_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='not_scheduled_to_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
