# Generated by Django 3.2.16 on 2022-12-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0029_pareto_not_scheduled_to_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='job_otg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job5', to='gemba.jobmodel2'),
        ),
    ]
