# Generated by Django 3.2.16 on 2022-12-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0030_pareto_job_otg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Hourly Calculation',
            },
        ),
        migrations.AlterModelOptions(
            name='hourmodel',
            options={'verbose_name': 'Hour'},
        ),
    ]
