# Generated by Django 3.2.16 on 2022-12-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0031_auto_20221230_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimegroup',
            name='calculation',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_settings', to='gemba.calculationmodel'),
        ),
    ]
