# Generated by Django 3.2.16 on 2022-12-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0032_downtimegroup_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimedetail',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
