# Generated by Django 3.2.16 on 2023-01-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0034_auto_20230102_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linehourmodel',
            name='shift',
            field=models.CharField(choices=[('--', 'No choice'), ('1 - Morning shift', '1 - Morning shift'), ('2 - Afternoon shift', '2 - Afternoon shift'), ('3 - Night shift', '3 - Night shift')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pareto',
            name='shift',
            field=models.CharField(choices=[('--', 'No choice'), ('1 - Morning shift', '1 - Morning shift'), ('2 - Afternoon shift', '2 - Afternoon shift'), ('3 - Night shift', '3 - Night shift')], default='--', max_length=32),
        ),
    ]
