# Generated by Django 3.2.16 on 2023-01-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0035_auto_20230104_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel2',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_group', to='gemba.downtimegroup'),
        ),
    ]
