# Generated by Django 3.2.16 on 2023-01-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0037_auto_20230106_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapdetail',
            name='output',
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='scrap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
