# Generated by Django 3.2.16 on 2023-01-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0038_auto_20230107_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodetail',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
