# Generated by Django 3.2.16 on 2023-01-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0039_paretodetail_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paretodetail',
            name='qty',
        ),
    ]
