# Generated by Django 3.2.16 on 2023-01-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0041_alter_jobmodel2_inner_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimegroup',
            name='calculation',
            field=models.CharField(choices=[('Total output, Total good', 'Total output, Total good'), ('Hourly Good, Scrap items', 'Hourly Good, Scrap items'), ('Meter, Scrap items', 'Meter, Scrap items')], default='Hourly Good, Scrap items', max_length=32),
        ),
        migrations.AlterField(
            model_name='downtimeuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_group', to='gemba.downtimegroup'),
        ),
    ]
