# Generated by Django 3.2.16 on 2023-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0042_auto_20230108_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=200)),
                ('num_users', models.IntegerField()),
            ],
        ),
    ]
