# Generated by Django 3.2.16 on 2023-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0043_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareto',
            name='availability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pareto',
            name='oee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pareto',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pareto',
            name='quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='linehourmodel',
            name='shift',
            field=models.CharField(choices=[('--', 'No choice'), ('Morning shift', 'Morning shift'), ('Afternoon shift', 'Afternoon shift'), ('Night shift', 'Night shift')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pareto',
            name='shift',
            field=models.CharField(choices=[('--', 'No choice'), ('Morning shift', 'Morning shift'), ('Afternoon shift', 'Afternoon shift'), ('Night shift', 'Night shift')], default='--', max_length=32),
        ),
    ]
