# Generated by Django 3.2.16 on 2023-01-13 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0045_auto_20230113_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimedetail',
            options={'verbose_name': 'Downtime Detail'},
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
