# Generated by Django 3.2.16 on 2023-01-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0046_auto_20230113_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimemodel',
            options={'verbose_name': 'Downtime Reason'},
        ),
        migrations.AlterModelOptions(
            name='linehourmodel',
            options={'verbose_name': 'Line Start Hour'},
        ),
        migrations.AlterModelOptions(
            name='lineuser',
            options={'verbose_name': 'User vs Line'},
        ),
        migrations.AlterModelOptions(
            name='scrapdetail',
            options={'verbose_name': 'Scrap Detail'},
        ),
        migrations.RemoveField(
            model_name='linehourmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='downtimedetail',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines4', to='gemba.line'),
        ),
        migrations.AddField(
            model_name='linehourmodel',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines1', to='gemba.line'),
        ),
        migrations.AddField(
            model_name='pareto',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines2', to='gemba.line'),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines3', to='gemba.line'),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='takt_time',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines5', to='gemba.line'),
        ),
        migrations.AlterField(
            model_name='jobmodel2',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linehourmodel',
            name='start',
            field=models.TimeField(),
        ),
    ]
