# Generated by Django 3.2.16 on 2023-01-20 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0047_auto_20230114_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtimedetail',
            old_name='datetime',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='paretodetail',
            old_name='datetime',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='scrapdetail',
            old_name='datetime',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='downtimedetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
