# Generated by Django 3.2.16 on 2023-01-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0049_downtimegroup_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationModel',
        ),
    ]
