# Generated by Django 3.2.16 on 2023-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0050_delete_calculationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Timer',
            },
        ),
    ]
