# Generated by Django 3.2.16 on 2023-01-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0052_alter_timer_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
