# Generated by Django 3.2.16 on 2023-01-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0057_auto_20230124_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtimedetail',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='jobmodel2',
            name='line',
        ),
        migrations.RemoveField(
            model_name='jobmodel2',
            name='target',
        ),
        migrations.RemoveField(
            model_name='jobmodel2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pareto',
            name='ops',
        ),
        migrations.AddField(
            model_name='downtimedetail',
            name='from_job',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='col_vector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pareto',
            name='ops_otg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='ops',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='rework',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='from_job',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scrapmodel',
            name='rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='line',
            name='calculation',
            field=models.CharField(choices=[('Total output, Total good', 'Total output, Total good'), ('Hourly Good, Scrap items, Inners', 'Hourly Good, Scrap items, Inners'), ('Hourly Good, Scrap items, Bags', 'Hourly Good, Scrap items, Bags'), ('Meter, Scrap items, Inners', 'Meter, Scrap items, Inners')], default='Hourly Good, Scrap items, Inners', max_length=32),
        ),
        migrations.CreateModel(
            name='JobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(default=0)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='gemba.jobmodel2')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines19', to='gemba.line')),
            ],
            options={
                'verbose_name': 'Job vs Line',
            },
        ),
    ]
