# Generated by Django 3.2.16 on 2023-01-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0058_auto_20230127_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='col_vector',
        ),
    ]
