# Generated by Django 3.2.16 on 2023-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0059_remove_line_col_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobline',
            name='factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='start_meter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='calculation',
            field=models.CharField(choices=[('Total output, Total good', 'Total output, Total good'), ('Hourly Good, Scrap items, Inners', 'Hourly Good, Scrap items, Inners'), ('Hourly Good, Scrap items, Bags', 'Hourly Good, Scrap items, Bags'), ('Meter, Scrap items', 'Meter, Scrap items')], default='Hourly Good, Scrap items, Inners', max_length=32),
        ),
        migrations.AlterField(
            model_name='paretodetail',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
