# Generated by Django 3.2.16 on 2023-02-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gemba', '0061_monthlyresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyresults',
            options={'verbose_name': 'Monthly Result'},
        ),
        migrations.AddField(
            model_name='scrapdetail',
            name='quarantined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paretodetail',
            name='output',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paretodetail',
            name='rework',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paretodetail',
            name='scrap',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuarantineHistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_qty', models.PositiveIntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('scrap', models.IntegerField(default=0)),
                ('pareto_id', models.PositiveIntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('pareto_date', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs6', to='gemba.jobmodel2')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines21', to='gemba.line')),
                ('scraps', models.ManyToManyField(to='gemba.ScrapDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quarantine Record',
            },
        ),
    ]
