# Generated by Django 3.2.16 on 2023-02-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0062_auto_20230208_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinehistorydetail',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
