# Generated by Django 3.2.16 on 2023-02-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0063_quarantinehistorydetail_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editors',
        ),
    ]
