# Generated by Django 3.2.16 on 2023-02-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0064_delete_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='target',
            field=models.IntegerField(default=75),
        ),
    ]
