# Generated by Django 3.2.16 on 2023-02-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0065_line_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='code',
        ),
    ]
