# Generated by Django 3.2.16 on 2023-02-27 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0066_remove_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodetail',
            name='finished',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
