# Generated by Django 3.2.16 on 2023-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0067_paretodetail_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodetail',
            name='availability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='oee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paretodetail',
            name='quality',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
