# Generated by Django 3.2.16 on 2023-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0069_alter_paretodetail_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='paretodetail',
            name='available_time',
            field=models.IntegerField(default=0),
        ),
    ]
