# Generated by Django 3.2.15 on 2022-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_jobupdate_operationmodel_relationmodel_stationmodel_toolmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmodel',
            name='job_list',
            field=models.ManyToManyField(blank=True, null=True, to='tools.RelationModel'),
        ),
    ]
