# Generated by Django 3.2.15 on 2022-10-14 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20221012_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
