# Generated by Django 3.2.15 on 2022-10-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_operationmodel_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationmodel',
            name='job',
        ),
    ]
