# Generated by Django 3.2.15 on 2022-10-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20221015_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs1', to='tools.jobmodel')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines1', to='tools.machinemodel')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations2', to='tools.stationmodel')),
            ],
            options={
                'verbose_name_plural': 'JobStations',
            },
        ),
    ]
