# Generated by Django 3.2.15 on 2022-10-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_jobstationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationModel',
        ),
    ]
