# Generated by Django 3.2.15 on 2022-10-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_delete_relationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='jobstationmodel',
            options={'verbose_name': 'Job Station'},
        ),
        migrations.AlterModelOptions(
            name='jobupdate',
            options={'verbose_name': 'Job update'},
        ),
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'verbose_name': 'Machine'},
        ),
        migrations.AlterModelOptions(
            name='operationmodel',
            options={'verbose_name': 'Tool change'},
        ),
        migrations.AlterModelOptions(
            name='stationmodel',
            options={'verbose_name': 'Station'},
        ),
        migrations.AlterModelOptions(
            name='toolmodel',
            options={'verbose_name': 'Tool'},
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
