# Generated by Django 3.2.15 on 2022-10-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20221019_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolmodel',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='toolmodel',
            name='station',
        ),
        migrations.AlterField(
            model_name='jobstationmodel',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jobs1', to='tools.jobmodel'),
        ),
        migrations.AlterField(
            model_name='jobstationmodel',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines1', to='tools.machinemodel'),
        ),
        migrations.AlterField(
            model_name='jobstationmodel',
            name='station',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stations2', to='tools.stationmodel'),
        ),
        migrations.AlterField(
            model_name='jobupdate',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='jobs2', to='tools.jobmodel'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines2', to='tools.machinemodel'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='station',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='tools.stationmodel'),
        ),
    ]
