# Generated by Django 3.2.15 on 2022-10-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_auto_20221021_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs2', to='tools.jobmodel'),
        ),
    ]
