# Generated by Django 3.2.15 on 2022-10-21 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20221021_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
