# Generated by Django 3.2.15 on 2022-10-21 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_auto_20221021_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='date',
            field=models.DateTimeField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
