# Generated by Django 3.2.15 on 2022-10-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20221021_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
