# Generated by Django 3.2.15 on 2022-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_alter_operationmodel_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmodel',
            name='tool_type',
            field=models.CharField(choices=[('T', 'Tool'), ('R', 'Rubber')], default='T', max_length=1),
        ),
    ]
