# Generated by Django 3.2.15 on 2022-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_operationmodel_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='tool_type',
            field=models.CharField(choices=[('Toll', 'Tool'), ('Rubber', 'Rubber')], default='Toll', max_length=64),
        ),
    ]
