# Generated by Django 3.2.16 on 2022-11-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_alter_jobmodel_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobupdate',
            old_name='meters',
            new_name='parts',
        ),
        migrations.RenameField(
            model_name='operationmodel',
            old_name='meters',
            new_name='parts',
        ),
    ]
