# Generated by Django 3.2.16 on 2022-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_auto_20221104_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobupdate',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
