# Generated by Django 3.2.16 on 2022-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0028_jobupdate_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
