# Generated by Django 3.2.16 on 2022-11-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0029_alter_jobupdate_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationmodel',
            name='parts',
        ),
        migrations.AddField(
            model_name='operationmodel',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
