# Generated by Django 3.2.16 on 2022-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0033_alter_jobupdate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
