# Generated by Django 3.2.16 on 2022-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0034_alter_operationmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='date',
            field=models.DateField(default='2022-11-05'),
        ),
    ]
