# Generated by Django 3.2.16 on 2022-11-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0035_alter_jobupdate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobupdate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='operationmodel',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='operationmodel',
            name='start_date',
        ),
    ]
