# Generated by Django 3.2.16 on 2022-11-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0039_auto_20221105_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmodel',
            name='tool_status',
            field=models.CharField(choices=[('Spare', 'Spare'), ('In use', 'In use'), ('Scrapped', 'Scrapped')], default='Spare', max_length=64),
        ),
    ]
