# Generated by Django 3.2.16 on 2022-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0040_toolmodel_tool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='inner_size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
