# Generated by Django 3.2.16 on 2023-01-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0042_auto_20221231_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobModel',
        ),
    ]
