# Generated by Django 3.2.16 on 2023-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0044_auto_20230106_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='machine_status',
            field=models.CharField(choices=[('Not in use', 'Not in use'), ('Productive', 'Productive')], default='Productive', max_length=64),
        ),
        migrations.AlterField(
            model_name='stationmodel',
            name='num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
