# Generated by Django 3.2.16 on 2023-01-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0047_alter_tooljobmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstationmodel',
            options={'verbose_name': 'Tool Station'},
        ),
        migrations.RemoveField(
            model_name='jobstationmodel',
            name='job',
        ),
    ]
