# Generated by Django 3.2.16 on 2023-01-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0048_auto_20230107_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodel',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines2', to='tools.machinemodel'),
        ),
    ]
