# Generated by Django 3.2.16 on 2023-01-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0049_stationmodel_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationmodel',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='operationmodel',
            name='station',
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='tool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.jobstationmodel'),
        ),
    ]
