# Generated by Django 3.2.16 on 2023-01-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0050_auto_20230115_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='tool',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.toolmodel'),
        ),
    ]
