# Generated by Django 3.2.16 on 2023-01-20 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0051_alter_operationmodel_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationmodel',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines3', to='tools.machinemodel'),
        ),
        migrations.AddField(
            model_name='operationmodel',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations2', to='tools.stationmodel'),
        ),
        migrations.AlterField(
            model_name='jobstationmodel',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations1', to='tools.stationmodel'),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 20, 16, 35, 821055)),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.toolmodel'),
        ),
    ]
