# Generated by Django 3.2.16 on 2023-01-21 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0052_auto_20230120_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 15, 20, 5, 218575)),
        ),
    ]
