# Generated by Django 3.2.16 on 2023-01-21 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0053_alter_operationmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 15, 22, 34, 280698)),
        ),
    ]
