# Generated by Django 3.2.16 on 2023-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0056_alter_operationmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
