# Generated by Django 3.2.16 on 2023-01-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0055_timer_completed'),
        ('tools', '0059_auto_20230122_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolstationmodel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines10', to='gemba.line'),
        ),
    ]
