# Generated by Django 3.2.16 on 2023-01-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0061_alter_stationmodel_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooljobmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
