# Generated by Django 3.2.16 on 2023-01-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gemba', '0056_jobmodel2_line'),
        ('tools', '0062_tooljobmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationmodel',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines12', to='gemba.line'),
        ),
    ]
