# Generated by Django 3.2.16 on 2023-01-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0064_alter_operationmodel_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationmodel',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='operationmodel',
            name='station',
        ),
    ]
