# Generated by Django 3.2.16 on 2023-01-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0066_auto_20230122_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineModel',
        ),
        migrations.RemoveField(
            model_name='stationmodel',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='stationmodel',
            name='num',
        ),
        migrations.AddField(
            model_name='toolstationmodel',
            name='tool_type',
            field=models.CharField(choices=[('Tool', 'Tool'), ('Rubber', 'Rubber')], default='Tool', max_length=64),
        ),
        migrations.AlterField(
            model_name='operationmodel',
            name='tool_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
